import { FormRPartA } from "../models/FormRPartA";

export const formrParta: FormRPartA = {
  id: "mock string",
  traineeTisId: "mock string",
  forename: "mock string",
  surname: "mock string",
  gmcNumber: "mock string",
  localOfficeName: "mock string",
  dateOfBirth: new Date(),
  gender: "mock string",
  immigrationStatus: "mock string",
  qualification: "mock string",
  dateAttained: new Date(),
  medicalSchool: "mock string",
  address1: "mock string",
  address2: "mock string",
  address3: "mock string",
  address4: "mock string",
  postCode: "mock string",
  telephoneNumber: "mock string",
  mobileNumber: "mock string",
  email: "mock string",
  isLeadingToCct: true,
  programmeSpecialty: "mock string",
  cctSpecialty1: "mock string",
  cctSpecialty2: "mock string",
  college: "mock string",
  completionDate: new Date(),
  trainingGrade: "mock string",
  startDate: new Date(),
  programmeMembershipType: "mock string",
  wholeTimeEquivalent: 0.69,
  submissionDate: "mock string",
  lastModifiedDate: "mock string",
  declarationType: "mock string",
  otherImmigrationStatus: "mock string"
};
