export const LOAD_TRAINEE_PROFILE_SUCCESS = "LOAD_TRAINEE_PROFILE_SUCCESS";
export const LOAD_TRAINEE_PROFILE_FAILURE = "LOAD_TRAINEE_PROFILE_FAILURE";
export const LOAD_INITIAL_VALUES_SUCCESS = "LOAD_INITIAL_VALUES_SUCCESS";
export const LOAD_INITIAL_VALUES_FAILURE = "LOAD_INITIAL_VALUES_FAILURE";
export const LOAD_REFERENCE_GENDER_SUCCESS = "LOAD_REFERENCE_GENDER_SUCCESS";
export const LOAD_REFERENCE_GENDER_FAILURE = "LOAD_REFERENCE_GENDER_FAILURE";
export const LOAD_REFERENCE_COLLEGES_SUCCESS =
  "LOAD_REFERENCE_COLLEGES_SUCCESS";
export const LOAD_REFERENCE_COLLEGES_FAILURE =
  "LOAD_REFERENCE_COLLEGES_FAILURE";
export const LOAD_REFERENCE_QUALIFICATIONS_SUCCESS =
  "LOAD_REFERENCE_QUALIFICATIONS_SUCCESS";
export const LOAD_REFERENCE_QUALIFICATIONS_FAILURE =
  "LOAD_REFERENCE_QUALIFICATIONS_FAILURE";
export const LOAD_REFERENCE_LOCAL_OFFICES_SUCCESS =
  "LOAD_REFERENCE_LOCAL_OFFICES_SUCCESS";
export const LOAD_REFERENCE_LOCAL_OFFICES_FAILURE =
  "LOAD_REFERENCE_LOCAL_OFFICES_FAILURE";
export const LOAD_REFERENCE_GRADES_SUCCESS = "LOAD_REFERENCE_GRADES_SUCCESS";
export const LOAD_REFERENCE_GRADES_FAILURE = "LOAD_REFERENCE_GRADES_FAILURE";
export const LOAD_REFERENCE_IMMIGRATION_STATUS_SUCCESS =
  "LOAD_REFERENCE_IMMIGRATION_STATUS_SUCCESS";
export const LOAD_REFERENCE_IMMIGRATION_STATUS_FAILURE =
  "LOAD_REFERENCE_IMMIGRATION_STATUS_FAILURE";
