export const LOAD_TRAINEE_PROFILE_SUCCESS = "LOAD_TRAINEE_PROFILE_SUCCESS";
export const LOAD_TRAINEE_PROFILE_FAILURE = "LOAD_TRAINEE_PROFILE_FAILURE";
export const LOAD_REFERENCE_GENDER_SUCCESS = "LOAD_REFERENCE_GENDER_SUCCESS";
export const LOAD_REFERENCE_GENDER_FAILURE = "LOAD_REFERENCE_GENDER_FAILURE";
export const LOAD_REFERENCE_COLLEGES_SUCCESS =
  "LOAD_REFERENCE_COLLEGES_SUCCESS";
export const LOAD_REFERENCE_COLLEGES_FAILURE =
  "LOAD_REFERENCE_COLLEGES_FAILURE";
export const LOAD_REFERENCE_QUALIFICATIONS_SUCCESS =
  "LOAD_REFERENCE_QUALIFICATIONS_SUCCESS";
export const LOAD_REFERENCE_QUALIFICATIONS_FAILURE =
  "LOAD_REFERENCE_QUALIFICATIONS_FAILURE";
export const LOAD_REFERENCE_LOCAL_OFFICES_SUCCESS =
  "LOAD_REFERENCE_LOCAL_OFFICES_SUCCESS";
export const LOAD_REFERENCE_LOCAL_OFFICES_FAILURE =
  "LOAD_REFERENCE_LOCAL_OFFICES_FAILURE";
export const LOAD_REFERENCE_GRADES_SUCCESS = "LOAD_REFERENCE_GRADES_SUCCESS";
export const LOAD_REFERENCE_GRADES_FAILURE = "LOAD_REFERENCE_GRADES_FAILURE";
export const LOAD_REFERENCE_IMMIGRATION_STATUS_SUCCESS =
  "LOAD_REFERENCE_IMMIGRATION_STATUS_SUCCESS";
export const LOAD_REFERENCE_IMMIGRATION_STATUS_FAILURE =
  "LOAD_REFERENCE_IMMIGRATION_STATUS_FAILURE";
export const LOAD_REFERENCE_CURRICULA_SUCCESS =
  "LOAD_REFERENCE_CURRICULA_SUCCESS";
export const LOAD_REFERENCE_CURRICULA_FAILURE =
  "LOAD_REFERENCE_CURRICULA_FAILURE";
export const LOAD_FORMR_PARTA_SUCCESS = "LOAD_FORMR_PARTA_SUCCESS";
export const LOAD_FORMR_PARTA_FAILURE = "LOAD_FORMR_PARTA_FAILURE";
export const LOAD_FORMR_PARTA_LIST_SUCCESS = "LOAD_FORMR_PARTA_LIST_SUCCESS";
export const LOAD_FORMR_PARTA_LIST_FAILURE = "LOAD_FORMR_PARTA_LIST_FAILURE";
export const LOAD_FORMR_PARTB_SUCCESS = "LOAD_FORMR_PARTB_SUCCESS";
export const LOAD_FORMR_PARTB_FAILURE = "LOAD_FORMR_PARTB_FAILURE";
export const LOAD_FORMR_PARTB_LIST_SUCCESS = "LOAD_FORMR_PARTB_LIST_SUCCESS";
export const LOAD_FORMR_PARTB_LIST_FAILURE = "LOAD_FORMR_PARTB_LIST_FAILURE";
export const LOAD_FORMR_PARTB_INITIAL_VALUES_SUCCESS =
  "LOAD_FORMR_PARTB_INITIAL_VALUES_SUCCESS";
export const LOAD_FORMR_PARTB_INITIAL_VALUES_FAILURE =
  "LOAD_FORMR_PARTB_INITIAL_VALUES_FAILURE";
export const FORMR_PARTB_NEXT_SECTION = "FORMR_PARTB_NEXT_SECTION";
export const FORMR_PARTB_PREVIOUS_SECTION = "FORMR_PARTB_PREVIOUS_SECTION";
